name: PR Preview

concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

env:
  PREVIEW_BRANCH: gh-pages
  SOURCE_DIR: ./
  UMBRELLA_DIR: pr-preview

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        id: preview-step
        with:
          source-dir: ${{ env.SOURCE_DIR }}
          preview-branch: ${{ env.PREVIEW_BRANCH }}
          umbrella-dir: ${{ env.UMBRELLA_DIR }}
          comment: true
