name: PR Preview

concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

env:
  PREVIEW_BRANCH: gh-pages

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        id: preview-step
        with:
          source-dir: ./
          preview-branch: ${{ env.PREVIEW_BRANCH }}
          comment: true
